### ISSUE TITLE
ES7 Decorator support on Readme

### ISSUE THREAD

**Issue by anaibol** [gyzerok/adrenaline#100]
Hi! Thanks for this interesting alternative to Relay!
I was asking me if there is currently support for ES7 decorators.
Thanks

**Comment by mattiasewers** [comment]
Yes there is, I'm using it as a decorator

**Comment by anaibol** [comment]
Great!

For those using redux / react-redux / redux-async-connect:

```js
import { connect } from 'react-redux'
import { container } from 'adrenaline'

@container({
    variables: (props) => ({
    id: props.userId,
  }),
  query: `
    query ($id: ID!) {
      user(id: $id) {
        displayName
      }
    }
  `
})
@connect(
  state => ({ user: state.auth.user })
)
export default class extends Component {
  render() {
    const { user, auth } = this.props
   ...
  }
}
```

And

```js
    <Adrenaline>
      <Provider store={store}>
        <App/>
      </Provider>
    </Adrenaline>
```
I think there could be an example with decorators on the readme

**Comment by gyzerok** [comment]
Yeah, I guess I need to mention it. Do think additional section with an example would be enough?

**Comment by anaibol** [comment]
I think yes, it would be enough :)

**Comment by gyzerok** [comment]
@anaibol can you come up with a PR ofr this?
