### ISSUE TITLE
Request for feedback: ESLint GraphQL plugin

### ISSUE THREAD

**Issue by stubailo** [gyzerok/adrenaline#104]
Hi! I noticed you talked a bit in the README about validating queries. I put together an ESLint plugin for this, which has a few benefits over tests:

1. See the error in your editor directly
2. Get a report about the exact line number where the error appears
3. This tool works with multiple GraphQL clients (Lokka/Relay/Apollo etc) so maybe we can work together on improving it

The plugin and docs are here: https://github.com/apollostack/eslint-plugin-graphql

Here's a screenshot with Relay:

![screenshot 2016-04-25 23 26 25](https://cloud.githubusercontent.com/assets/448783/14829785/23adce2a-0ba2-11e6-8e95-7c20df301ea6.png)

Curious what you think about this approach! I'm looking to improve it, so any feedback would be appreciated.

See a code sample of using with Relay here: https://github.com/facebook/relay/pull/1088

**Comment by gyzerok** [comment]
Hi @stubailo,

This is great! My case was not about actually seeing errors in IDE, but to be able to find exact parts of my application that need to be updated after schema update. So this was more about CLI interface. However eslint could be run within CLI, so your approach is really great :)
