### ISSUE TITLE
createSmartComponent left in the readme

### ISSUE THREAD

**Issue by kevinsimper** [gyzerok/adrenaline#109]
import { createSmartComponent } from 'adrenaline';

but it is never used anywhere

**Comment by gyzerok** [comment]
Hi @kevinsimper!

Currently readme reflects release candidate docs. So you have two options right now:
 * keep using `0.11` version, then you can find docs in [corresponding tag](https://github.com/gyzerok/adrenaline/tree/v0.11.1)
 * use release candidate, then you need to `npm install --save adrenaline@1.0.0-rc1`
