### ISSUE TITLE
_this.setState({ data: null } in 1.0.0-rc1

### ISSUE THREAD

**Issue by cameronbourke** [gyzerok/adrenaline#112]
Hey, firstly this is a really nice subset of `Relay`. The dev experience with this has been a lot better than that of working with `Relay`. One small issue I've ran into is that currently when you install `1.0.0-rc-1` I get the following within `./node_modules/adrenaline/lib/components/container.js`

```
_this.setState({ data: null }, function () { // should be _this.setState({ isFetching: true }
  _this.context.query(query, variables).catch(function (err) {
    console.err(err); // eslint-disable-line
  }).then(function (data) {
    return _this.setState({ data: data });
  });
});
```

**Comment by gyzerok** [comment]
Hello @cameronbourke!

Thanks for opening an issue. Could you try `npm install adrenaline@1.0.0-rc2`?

**Comment by cameronbourke** [comment]
@gyzerok Yep, that fixed it! Cheers.

I have another issue in regards to how when `isFetching` is true, the `data` is always false. However, I'll open a new issue that elaborates on that.

**Comment by gyzerok** [comment]
Okey, good to know
