### ISSUE TITLE
The state is dropped every time a new fetch is happening

### ISSUE THREAD

**Issue by cameronbourke** [gyzerok/adrenaline#113]
Currently, every time a new fetch is triggered after a mutation, the state is set to undefined as soon as the fetch commences, and then set back once the data is returned from the server.

The following screenshot shows how `viewer` is `undefined` on the initial fetch for the app, but once a `todo` is added (in the example app in this repo), `viewer` becomes `undefined` again while `isFetching` is set to `true`.

<img width="1280" alt="screen shot 2016-06-30 at 6 39 07 pm" src="https://cloud.githubusercontent.com/assets/7464366/16484659/be1f7dee-3efd-11e6-96cb-de30b69c7066.png">

For reference, I'm logging from within the render of  the `TodoApp` component:
```
render() {
    const { viewer, isFetching } = this.props;
    console.log('viewer: ', viewer, '-----> isFetching: ', isFetching);
```

Is this the expected behaviour, and if so, why would that be the case instead of the alternative where only once the new state has been returned from the server, does the new state overwrite the old state.

**Comment by gyzerok** [comment]
Yeah, thats true and thats by design. The idea of Adrenaline is to not optimize stuff, but to provide simpler developer experience.

So when you use Adrenaline you should address this problem yourself. One way to do it is to store this data in the containers state and update it by your own. In this case if your rendering would depend on the state, component wont rerender on each fetch.

**Comment by cameronbourke** [comment]
Okay, cool! How does this provide a simpler developer experience though? From my perspective, having to deal with that state myself creates an experience that is inherently more complex.

What issues would arise from the library handling this? There may be genuine reasons not to do so, but I may not have enough context obviously about the internals to know.

**Comment by gyzerok** [comment]
This is all about how complex API is. In terms you highly need optimized refetching strategies you can go with Relay. However you would need to deal with more complex API. So it's all about your use case and  trade-offs.

**Comment by cameronbourke** [comment]
This is the part that has confused me.
>  However you would need to deal with more complex API

By **not** dropping the data while Adrenaline `isFetching`, the API would become simpler, would it not? I would not have to handle the state myself, therefore I would gain more from this library.

You haven't clearly articulated why updating the state **only** after the request has returned is not the default behaviour? Are you saying the source code for Adrenaline's API would be more complex if the state wasn't dropped?

**Comment by gyzerok** [comment]
@cameronbourke I see now what you mean. To be honest I do not quite remember reasoning behind this decision :)

Okey, let's imagine we do not set data state to null in the middle of fetching. What potential downsides can you see around it? May there be some cases which would became harder or even impossible to implement having this behaviour?

**Comment by gyzerok** [comment]
So I'm quite free to change this behaviour, I just want to discuss a little pros and cons of this change.

**Comment by cameronbourke** [comment]
@gyzerok I cannot think of any potential downsides because I assume that if someone was doing any complex caching or data transforms they would definitely be storing a copy of the data passed down anyways.

On the other hand, if the default behaviour is to not store the data within their root component, then they are able to use the data passed down as source of truth. Which is nice in my opinion because I do not need to repeatedly update my copy of the data if it is going to be exactly the same as what is passed down to me from `Adrenaline`.

**Comment by gyzerok** [comment]
@cameronbourke does it looks right now?

**Comment by cameronbourke** [comment]
@gyzerok Yep! Sure does, look forward to the next `rc`. Thanks man.

**Comment by gyzerok** [comment]
I've finally decided, that it would be easier for people to install and use the library with non-rc release. So feel free to try `1.0.1` :)
