### ISSUE TITLE
Can't mutate data without query

### ISSUE THREAD

**Issue by romainPrignon** [gyzerok/adrenaline#115]
Hello

I want to mutate my data with this simple snippet:
```js
this.props.mutate({
  mutation: someMutationVariable
})
```

But, I don't understand why I need to declare a query in the container for this component.
If I don't declare a  container, I can't get the mutate props.

Could you be more explicit ?

Thanks a lot

**Comment by gyzerok** [comment]
Hello @romainPrignon 

I don't quite understand what do you mean by being more explicit. As for your problem the idea is you declare all "actions" which runs mutations (you may also call it side-effects) in the closest ancestor container and then pass them to children if needed.

```js
// Input.jsx
class Input extends React.Component {
  render() {
    return <input type="text" onChange={this.onTextChange} />
  }
}

// Parent.jsx
class Parent extends React.Component {
  handleTextUpdate = (newText) => {
    this.props.mutate({
      mutation: yourMutationHere,
      { text: newText }
    });
  }
  
  render() {
    return <Input onTextChange={this.handleTextUpdate} />
  }
}

export default container({ ... })(Parent);
```
