### ISSUE TITLE
How to query data in container

### ISSUE THREAD

**Issue by yaodingyd** [gyzerok/adrenaline#119]
This may be a dumb question, but how can I query data after initial query fired? Do I have to use `mutate`? Can I somehow re-trigger `query`?

Thanks!

**Comment by gyzerok** [comment]
Hello @yaodingyd!

What is your use case? How would minimalistic example look like?

**Comment by yaodingyd** [comment]
@gyzerok I started with adrenaline (with a existing project) and skipped Relay, so pardon me if this is too basic.

My app  is like a search app and my container would show some initial data, but when user input some criteria I need to do query from database. They would be the same query as initial query(variable would change though), so how would I achieve this?

Thanks for answering! BTW, Adrenaline is really easy to start with, good job!

**Comment by gyzerok** [comment]
Hi @yaodingyd and sorry for a bit of a long answer

The question is totally valid, I just wanted to know your case better, so I can address your question better.

In general back in the days the idea was to make container components kind of "pure" in as sense that data dependencies are based only on props. So in your case if you want to run new query you need to pass another property to your component.

There are several ways to do it:
1. If you are using router then in your case you most likely want retain search string within your route (`?search=myquery`) so user will see results for the same query if press back browser button. In this case router will pass this search string alongside props to your container component and query will be re-executed.
2. You can separate component with input field from component which render search result and then each time input field got changed you will pass new property to container and query will be re-executed.

Does it help you in solving your issue?

**Comment by yaodingyd** [comment]
@gyzerok Thanks for your answer! I think solution.2 will suit my case well.
