### ISSUE TITLE
Lack of tests

### ISSUE THREAD

**Issue by fabiosantoscode** [gyzerok/adrenaline#12]
As a response to [your comment](https://github.com/rackt/redux/issues/464#issuecomment-142228611), I'd like to share this concern with you.

Besides making sure stuff works both on the client and on the server, tests can be pretty helpful to understand how something can be used, kicking in where the documentation is vague and the source to hard to read.

**Comment by gyzerok** [comment]
@fabiosantoscode Thanks for your feedback. The main reason of test lacking is lack of experience in writing tests from my side.

**Comment by fabiosantoscode** [comment]
Since the purpose of adrenaline is to glue some stuff together and provide a good interface, I think it'd be nice to test that the interface gives good errors, and that the stuff it's supposed to be gluing together is called with the correct arguments. The latter can be easily done with sinon.js.

No library is complete without tests.

**Comment by gyzerok** [comment]
@fabiosantoscode Yes, you are absolutely right. I guess I would try to cover as much as possible code to 1.0. For now even API and functionality is incomplete.
