### ISSUE TITLE
Example's WebPack Cannot Resolve All Modules

### ISSUE THREAD

**Issue by tylermauthe** [gyzerok/adrenaline#15]
When the root level index.js is run in the example, I receive a bunch of errors because the WebPack Dev Server cannot resolve: 'react', 'babel', and 'babel-runtime/helpers/interop-require-default'.

Full gist here: https://gist.github.com/tylermauthe/8a5b088a65b757987b85

I was able to resolve react by adding it to the `package.json` and re-running `npm install` and I do not have time right now to figure out the rest. :grinning:

**Comment by gyzerok** [comment]
@tylermauthe I there is separate package.json inside example folder.
In order to run exampe now you need to do this:
```
cd example
npm i
node index.js
```

**Comment by gyzerok** [comment]
Oh sorry, I see now the missing dependencies. Gonna fix it ;)
