### ISSUE TITLE
Optimistic mutations

### ISSUE THREAD

**Issue by ForbesLindesay** [gyzerok/adrenaline#5]
I really like the idea of this library.  One of the features I was really keen to get is optimistic updates for mutations.  To that end I've built [redux-optimist](https://github.com/ForbesLindesay/redux-optimist).  It would be really interesting to try integrating that library with this one.

**Comment by gyzerok** [comment]
@ForbesLindesay yeah, sounds cool! The reason I do not implement optimistic mutations is the one that there are more things with higher priority. Like remove necessity of resolve with if statements. But optimistic update would definitely appear. And if `redux-optimist` works cool OU comes even faster :)

**Comment by gyzerok** [comment]
This stuff is currently discarded.
