### ISSUE TITLE
NPM out of date with Library

### ISSUE THREAD

**Issue by jherr** [gyzerok/adrenaline#50]
It looks like the npm version of this, particular in lib/index.js has a lot fewer exports than what is in src/index.js.

**Comment by jherr** [comment]
If I do `npm run prepublish` locally I get a lot more exports in `lib/index.js`.

**Comment by BBB** [comment]
@jherr It seems as if the project is having a major rehaul. For example #16 changed a great deal of the api (for the better). Most people should be using the version in npm and browsing the code base at that commit for now. https://github.com/gyzerok/adrenaline/tree/v0.11.1 

If you need some features from master, pin your npm module to the commit sha. but be warned, the api might change frequently before v1.0.0 is released.

Unless @gyzerok thinks differently?

**Comment by gyzerok** [comment]
@jherr We gonna introduce a huge API changes [here](https://github.com/gyzerok/adrenaline/pull/59) to decouple Adrenaline from GraphQL and Redux.

I'm gonna revisit this before next release.
