### ISSUE TITLE
Automatically resolve through cache on client

### ISSUE THREAD

**Issue by skosch** [gyzerok/adrenaline#79]
Hi,

I've lost track of the commits ahead of the master branch, but I'm wondering what the state of affairs is with the client-side `resolve` function.

At least superficially it appears that we could simply pull data from the cache based on the type: e.g.
* for some user defined object type, we return `root[thisObject[thisField].type.name][thisObject[thisField].id]`,
* for a `GraphQLList`, we return `thisObject[thisField].map(id => root[thisObject[thisField].type.name][id])`,
* etc.

I have little GraphQL experience. Am I being naive here, or is this the right way to approach this, at least in theory? And/or have you something in mind/on paper/stashed away in a PR somewhere already for me to look at, if I wanted to take a stab at this?

Cheers! (And hats off for a very worthwhile project!)

**Comment by gyzerok** [comment]
Hi, @skosch!

Currently we are trying to get API stable so there is nothing in GraphQL resolving in particular. I've done a step forward in implementing GraphQLAdaptor but this code is not in repo yet. I would share it on holidays.

So you are free to investigate in automatic cache resolving for now. I would like to see your thoughts on this. Feel free to make a PR.

**Comment by gyzerok** [comment]
I've discarded the idea of cache on the client.
