### ISSUE TITLE
Do you plan to continue working on the project?

### ISSUE THREAD

**Issue by wss-world** [gyzerok/adrenaline#83]
I am interested in your work! Thank you))

**Comment by gyzerok** [comment]
Thanks @wss-world!

Sure, we are working on a new API with @pcwinters right now. You can check https://github.com/gyzerok/adrenaline/pull/59 to see some changes. We are moving a little bit slow right now, but I hope we would have a better progress in upcoming weeks.

**Comment by wss-world** [comment]
Well, I'm glad to hear that.
