### ISSUE TITLE
Store creation

### ISSUE THREAD

**Issue by gyzerok** [gyzerok/adrenaline#88]
The point of this discussion is to choose the better way of store creation and implement it within top-level API.

## Using separate key in Redux store to be able manage more than 1 reducer

This is originally @pcwinters idea. I make here just a dirty copy of his thoughts and waiting for him to clarify things by himself.

```js
const adrenalineKey = "someAdrenalineStateKey";
const stateSelector = (state)=>state[adrenalineKey]

const adaptor = createAdaptor(stateSelector);
const store = createStore(combineReducers({
  [adrenalineStateKey]: adaptor.reduce
}));

<ReduxStoreProvider store={store}>
  <AdrenalineProvider adaptor={adaptor}>
    {/* my app stuffs */}
  </AdrenalineProvider>
</ReduxStoreProvider>
```

**Pros:**
* We can easily use Adrenaline with React-Redux. Obtain data from both and manage local state inside Redux.
* We can use multiple Adaptors with different endpoints.

**Cons:**
* We are tightly coupled with Redux

@pcwinters feel free to add your pros and cons.

**Note:** In this case we need to somehow change current `Adaptor` API to be able to pass down `store` and case of this store. This need to be discussed if we chose this way.

## Create store inside Adaptor

This is how I'm currently using Adrenaline in my project.

```js
import { createStore } from 'redux';

const UPDATE_CACHE = 'UPDATE_CACHE';

function reducer(state = {}, { type, payload }) {
  switch (type) {
    case UPDATE_CACHE:
      return {
        ...state,
        ...payload.data,
      };
    default:
      return state;
  }
}

export default function createAdaptor(endpoint) {
  const store = createStore(reducer);

  return {
    resolve(queries, args) {},
    subscribe(listener) {},
    shouldComponentUpdate() {},
  };
}
```

**Pros:**
* We can easily use Adrenaline with React-Redux. Obtain data from both and manage local state inside Redux.
* We can use multiple Adaptors with different endpoints.
* Developer is completely unaware of what state management is using inside Adrenaline
* We are not coupled with Redux

**Cons:**
* If you want to somehow mix data from Adrenaline cache and another state manager you'll be unable to do it (from first perspective)

@pcwinters Does this alternative works for your particular use case?

**Comment by gyzerok** [comment]
## How to resolve data from different endpoints for REST

To solve this issue I've wrote custom Adaptor with following logic:
* If `$endpoint` isn't specified use default Adaptor endpoint
* If `$endpoint` specified use it to resolve data

```js
export default createContainer(SearchBox, {
  args: ({ location }) => ({
    q: location.q,
    region_id: location.region,
  }),
  query: (args) => ({
    firms: {
      $endpoint: 'http://different.com/catalog/branch/search',
      ...args,
    },
    geos: {
      ...args,
    }
  }),
});
```

**Comment by pcwinters** [comment]
> How to resolve data from different endpoints for REST

Consider that it might not only be a matter of different endpoints but of different strategies. REST API's tend to be inconsistent. I have some code in my fork that implements a composable adaptor. The args and queries are namespaced and it delegates to the correct strategy. I use Adrenaline like this to load data from different APIs and with different query structures, fetch and cache strategies, and normalization; but when defined together as container requirements, all of the data is updated by Adrenaline on the same lifecycle events.

**Comment by pcwinters** [comment]
> Create store inside Adaptor

There's only one way I can see this being viable, but I feel like it's too complicated. Adrenaline would have to [compose](http://rackt.org/redux/docs/api/compose.html) itself somehow. Do you use other middleware, reducers, devtools in your application?

I don't believe Adrenaline should concern itself with bootstrapping your application in any way. It should co-exist in a much larger application and keep out of the store. The only suggestion I would make, is that an adaptor's reducer become part of the adaptor API. Most of the time the reducer could be a static function, but in the composed strategy case I mentioned above, I let the adaptor delegate to reducers as well!

**Comment by gyzerok** [comment]
> Do you use other middleware, reducers, devtools in your application?

I found myself not using Redux at all while using Adrenaline. I store UI state inside Container's `this.state` and lie all the data state management to the Adrenaline. That's why I do not use any middlewares or devtools.

**Comment by gyzerok** [comment]
@pcwinters after thinking a little bit more on your idea I now found it as a better choice. 

Honestly I don't like following part
```js
const adrenalineKey = "someAdrenalineStateKey";
const stateSelector = (state)=>state[adrenalineKey]

const adaptor = createAdaptor(stateSelector);
const store = createStore(combineReducers({
  [adrenalineStateKey]: adaptor.reduce
}));
```
How can we express it in other way to reduce complexity?

**Comment by gyzerok** [comment]
Maybe this way:
```js
const adrenalineKey = "someAdrenalineStateKey";

const adaptor = createAdaptor(adrenalineKey, 'http://endpoint.com');
const store = createStore(combineReducers({
  [adrenalineStateKey]: adaptor.reduce
}));
```

**Comment by gyzerok** [comment]
I think we need to imagine 2 or 3 alternatives and then think about them.

**Comment by pcwinters** [comment]
@gyzerok, take a look at #89 , specifically the section in the [README](https://github.com/gyzerok/adrenaline/tree/api_readme#adrenalineprovider-getstate-subscribe-dispatch) about [`<AdrenalineProvider>`](https://github.com/gyzerok/adrenaline/tree/api_readme#adrenalineprovider-getstate-subscribe-dispatch)
