### ISSUE TITLE
Bundle collected, but this does not exist anywhere.

### ISSUE THREAD

**Issue by Xurma2** [gyzerok/adrenaline#93]
Hi
![image](https://cloud.githubusercontent.com/assets/5157416/13365062/e2b30a76-dce3-11e5-9b6a-710619d47c72.png)

What to do?
I run through the node index.js

I was try 
localhost:3000/example/graphql

this doesnt work

**Comment by gyzerok** [comment]
In the upcoming release candidate this should work correctly.
