### ISSUE TITLE
Test utils in index.js bloat the codebase by roughly 100kb

### ISSUE THREAD

**Issue by grgur** [gyzerok/adrenaline#94]
First of all, thank you for all your fine work! You made it fun and extremely useful to use gQL without Relay.

One of the main reasons to opt for Adrenaline over React is the sheer bundle size, given that Relay is some 200kB worth of minified code. However, Adrenaline (the github, not the npm version - which is even worse) doesn't show that benefit when used as recommended.

This particular line will make sure my production build is roughly 100kB larger
```
export TestUtils from './test-utils';
```

To fight it, I load modules like this:
```
import Adrenaline from 'adrenaline/lib/components/Adrenaline';
import container from 'adrenaline/lib/components/container';
import presenter from 'adrenaline/lib/components/presenter';
```

Perhaps it would be a nice idea to not export TestUtils in the main index.js and just have users know how to import them individually? Any thoughts on that?

**Comment by gyzerok** [comment]
Hi, @grgur!

I've mentioned out of sync with npm in README to reduce confusion for now.
I'm going to release 1.0-rc0 as soon as I come with appropriate docs and some minor fixes. For sure I would check why TestUtils expand bundle size and fix that.

Thanks for your input!

**Comment by gyzerok** [comment]
I've fixed that, so test utils are no more exposed by default, also I've added some documentation about using them inside readme.

Do you think it looks right?

**Comment by grgur** [comment]
Beautiful! Thanks a lot for taking care of this :) :+1:

**Comment by gyzerok** [comment]
@grgur I am thinking about making early release rc0 today. So any feedback about usage would be extremely helpful.

**Comment by grgur** [comment]
Externalizing network layer was a brilliant decision as it helped add more logic (such as caching). Kudos for that. At this point I don't have any further requests, but I'll stay in touch. Hopefully with PRs as well ;)
