### ISSUE TITLE
Should query() be exposed in container?

### ISSUE THREAD

**Issue by grgur** [gyzerok/adrenaline#95]
Do you think the `query` [method from container](https://github.com/gyzerok/adrenaline/blob/master/src/components/container.jsx#L62) should be exposed to the decorated component? I wonder if there's a use case for containers querying gql on their own.

**Comment by gyzerok** [comment]
I guess this may break an idea of declarative data descriptions. This means that you need to query data imperatively within your handlers or lifecycle hooks. In my mind this bring you towards less maintainability. It's like trying to modify your DOM with jQuery inside your React application.

Personally I have not had any cases where I need such functionality.

**Comment by Justkant** [comment]
And what about a force refetching method ? Is that already possible ?

**Comment by gyzerok** [comment]
@Justkant currently it's working only in force refetching mode. I've ended up with a solution to completely remove cache. If you need tricky cache strategy than probably you need to use Relay. However you can achieve simple memoization passing different `networkLayer` to the `<Adrenaline />` component.

**Comment by grgur** [comment]
@Justkant I agree with @gyzerok, for smart (but session based) cache management I would turn to Relay. However, Adrenaline might give you easier access to requests and responses where you could implement simple, but very effective, persistent cache.

This useful [breakdown on how Relay normalizes data](https://github.com/reactjs/redux/issues/464#issuecomment-142933911) got me want to learn more about how to effectively manage cache without having to implement _advanced trickery_.

**Comment by Justkant** [comment]
Thanks for your answers.

In my case, I started building a Relay app and a GraphQL server using RethinkDB during the last month.
It was easy at first but the lack of real time support through subscriptions and client side states management in relay made me go back to a simpler REST API (socket.io) backend & Redux for the app.
When I saw Adrenaline I was thinking: 'This is the bridge between redux and GraphQL for declarative state management in my app'. Unfortunately you ended up removing the cache layer.

Do you planning on some solutions for caching with redux ?

**Comment by gyzerok** [comment]
@Justkant currently Adrenaline is not connected to Redux at all. However you can easily use both in your application. Right now I do not planning any caching implementation cause Relay already do it. 

My goal in that project is to provide simpler API by removing some not widely necessary optimizations. I'd like to release 1.0 first and see folks feedback on this. So I am going to stop some decisions until this happens.

**Comment by Justkant** [comment]
I understand your motivation here and I'm aware that I can build with Adrenaline and Redux but I lose the hot reloading of the states downloaded by Adrenaline. Hot reloading is one the easy cool feature of Redux and I'd like to get that with a GraphQL client.
I will probably try to implement one if I find some time to do so.
Anyway you did a good job exploring a simpler API and I wish you good luck for the 1.0 release.
