### ISSUE TITLE
client cache support

### ISSUE THREAD

**Issue by tonytonyjan** [gyzerok/adrenaline#99]
Has client cache been implemented? I found the issue #20 closed, but it seems it's not done in 1.0.0-rc yet.

I want the `<Profile>` page to load and display some user data:

``` jsx
<Route path="/dashboard" component={Dashboard}>
  <IndexRoute component={Profile} />
  <Route path="posts" component={Posts} />
  ......
</Route>
```

query:

``` graphql
query {
  me {
    username,
    email,
    avatar
  }
}
```

The result is, query will be sent every time I navigate to other pages an back to `Profile` again. I wonder if I have missed something or it just not implemented yet.

**Comment by gyzerok** [comment]
Yeah you are right, there is no caching at the moment. While working with Adrenaline myself I've came with idea that I need to decide between complex API and lack of caching. I decided to remove cache to achieve a simpler API. If you hardly need caching I guess Relay is appropriate choice. But first ask yourself if you truly need it and why.

**Comment by stubailo** [comment]
Apollo Client can be a good alternative if you want caching: https://github.com/apollostack/apollo-client

Currently it caches root queries but we expect to add more Relay-like features soon, while trying to keep the complexity down.

**Comment by kbaird5** [comment]
Do you have examples of taking the query results and storing in Redux? Is the network layer where you would do this? Or are there planned extensions to @container()?
